version: '3.8'

services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "3050:80"
    networks:
      - node-webapp-network

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
      target: development
    volumes:
      - /app/node_modules
      - ./api:/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_password
      - DB_DATABASE=admin
    networks:
      - node-webapp-network

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - node-webapp-network

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge